apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  labels:
    app: wordpress
    tier: frontend
  namespace: project-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
        - name: my-container
          image: wordpress:php8.2-apache
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /var/www/html
              name: wordpress-efs-volume
          env:
            - name: WORDPRESS_DB_HOST
              value: mysql-service
            - name: WORDPRESS_DB_USER
              value: wordpress
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                 name: mysql-secret-password
                 key: password
            - name: WORDPRESS_DB_NAME
              value: wordpress
      volumes:
        - name: wordpress-efs-volume
          persistentVolumeClaim:
            claimName: wordpress-pvc